/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Ventanas;

import java.awt.Component;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.UIManager;

/**
 *
 * @author John
 */
public class Encuesta extends javax.swing.JFrame {
public static int Referencia = 0;
public static int PuntosAcumuladosParciales = 0;
public static int PuntosAcumulados = 0;
    /**
     * Creates new form Encuesta01
     */
    public Encuesta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloencuesta = new javax.swing.JLabel();
        p1 = new javax.swing.JLabel();
        p6 = new javax.swing.JLabel();
        p2 = new javax.swing.JLabel();
        p3 = new javax.swing.JLabel();
        p4 = new javax.swing.JLabel();
        p5 = new javax.swing.JLabel();
        Pregunta1 = new javax.swing.JComboBox();
        Pregunta2 = new javax.swing.JComboBox();
        Pregunta3 = new javax.swing.JComboBox();
        Pregunta5 = new javax.swing.JComboBox();
        Pregunta6 = new javax.swing.JComboBox();
        Pregunta4 = new javax.swing.JComboBox();
        next = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        parar = new javax.swing.JButton();
        cancelar = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(358, 18));
        setName("[358, 18]"); // NOI18N

        tituloencuesta.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        tituloencuesta.setText("Competencias del Postulante");

        p1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        p1.setText("1. ¿Cuánta experiencia cree tener en su área de trabajo?");
        p1.setAlignmentX(0.5F);
        p1.setAutoscrolls(true);
        p1.setMaximumSize(new java.awt.Dimension(500, 68));
        p1.setMinimumSize(new java.awt.Dimension(500, 68));
        p1.setName(""); // NOI18N

        p6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        p6.setText("6. ¿Qué nivel de aprendizaje cree que usted tiene?");
        p6.setAlignmentX(0.5F);
        p6.setAutoscrolls(true);
        p6.setMaximumSize(new java.awt.Dimension(500, 68));
        p6.setMinimumSize(new java.awt.Dimension(500, 68));
        p6.setName(""); // NOI18N

        p2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        p2.setText("2. ¿Cuanto ha tratado de mejorar en su área de trabajo?");
        p2.setAlignmentX(0.5F);
        p2.setAutoscrolls(true);
        p2.setMaximumSize(new java.awt.Dimension(500, 68));
        p2.setMinimumSize(new java.awt.Dimension(500, 68));
        p2.setName(""); // NOI18N

        p3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        p3.setText("3. ¿Tiene grandes ganas de trabajar, le entusiasma lo que hace?");
        p3.setAlignmentX(0.5F);
        p3.setAutoscrolls(true);
        p3.setMaximumSize(new java.awt.Dimension(500, 68));
        p3.setMinimumSize(new java.awt.Dimension(500, 68));
        p3.setName(""); // NOI18N

        p4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        p4.setText("4. ¿Que tanto se adapta al ritmo de la empresa?");
        p4.setAlignmentX(0.5F);
        p4.setAutoscrolls(true);
        p4.setMaximumSize(new java.awt.Dimension(500, 68));
        p4.setMinimumSize(new java.awt.Dimension(500, 68));
        p4.setName(""); // NOI18N

        p5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        p5.setText("5. ¿Qué tan empático se considera?");
        p5.setAlignmentX(0.5F);
        p5.setAutoscrolls(true);
        p5.setMaximumSize(new java.awt.Dimension(500, 68));
        p5.setMinimumSize(new java.awt.Dimension(500, 68));
        p5.setName(""); // NOI18N

        Pregunta1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10" }));
        Pregunta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pregunta1ActionPerformed(evt);
            }
        });

        Pregunta2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10" }));
        Pregunta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pregunta2ActionPerformed(evt);
            }
        });

        Pregunta3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10" }));
        Pregunta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pregunta3ActionPerformed(evt);
            }
        });

        Pregunta5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10" }));
        Pregunta5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pregunta5ActionPerformed(evt);
            }
        });

        Pregunta6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10" }));
        Pregunta6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pregunta6ActionPerformed(evt);
            }
        });

        Pregunta4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10" }));
        Pregunta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pregunta4ActionPerformed(evt);
            }
        });

        next.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/siguiente.png"))); // NOI18N
        next.setText("Siguiente");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/competencias.png"))); // NOI18N

        parar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/parar.png"))); // NOI18N
        parar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pararActionPerformed(evt);
            }
        });

        cancelar.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        cancelar.setText("Cancelar Encuesta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tituloencuesta)
                        .addGap(20, 602, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(p5, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Pregunta5, 0, 125, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Pregunta3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Pregunta1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(p3, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Pregunta2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(p4, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p6, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Pregunta4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Pregunta6, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(cancelar)
                                            .addComponent(parar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(36, 36, 36))
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(116, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pregunta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tituloencuesta)
                            .addComponent(cancelar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(parar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(89, 89, 89)
                        .addComponent(next))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pregunta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pregunta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pregunta4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pregunta5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pregunta6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Pregunta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pregunta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pregunta1ActionPerformed

    private void Pregunta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pregunta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pregunta2ActionPerformed

    private void Pregunta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pregunta3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pregunta3ActionPerformed

    private void Pregunta5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pregunta5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pregunta5ActionPerformed

    private void Pregunta6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pregunta6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pregunta6ActionPerformed

    private void Pregunta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pregunta4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pregunta4ActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        
        
        if (Referencia == 0){
        PuntosAcumuladosParciales = PuntosAcumuladosParciales 
        + (Integer.parseInt((String)Pregunta1.getSelectedItem())
        + Integer.parseInt((String)Pregunta2.getSelectedItem())
        + Integer.parseInt((String)Pregunta3.getSelectedItem())
        + Integer.parseInt((String)Pregunta4.getSelectedItem())
        + Integer.parseInt((String)Pregunta5.getSelectedItem())
        + Integer.parseInt((String)Pregunta6.getSelectedItem())); 
        }        
        
        Referencia++;
        
        /*Competencias*/        
        if (Referencia == 1){            
            tituloencuesta.setText("Competencias del Postulante");
            p1.setText("<html><center>7. ¿Qué nivel de adaptación al ambiente laboral posee?</center></html>");
            p2.setText("<html><center>8. ¿Qué tan líder usted podría ser?</center></html>");
            p3.setText("<html><center>9. ¿Qué tan a menudo prevé cambios a futuro?</center></html>");
            p4.setText("<html><center>10. ¿Posee capacidades para la negociación?</center></html>");
            p5.setText("<html><center>11. ¿Cree ser capaz de dominar la materia que <br>le competerá, para poder lidiar con una orientación <br> o guía al cliente de manera exitosa?</center></html>");
            p6.setText("<html><center>12. ¿Qué tan bien puede usted manejar la presión en<br> el ambiente laboral?</center></html>");
            Pregunta1.setSelectedIndex(0);
            Pregunta2.setSelectedIndex(0);
            Pregunta3.setSelectedIndex(0);
            Pregunta4.setSelectedIndex(0);
            Pregunta5.setSelectedIndex(0);
            Pregunta6.setSelectedIndex(0); 
        }
        
        /*Habilidades*/        
        if (Referencia == 2){           
            
            PuntosAcumuladosParciales = PuntosAcumuladosParciales 
            + (Integer.parseInt((String)Pregunta1.getSelectedItem())
            + Integer.parseInt((String)Pregunta2.getSelectedItem())
            + Integer.parseInt((String)Pregunta3.getSelectedItem())
            + Integer.parseInt((String)Pregunta4.getSelectedItem())
            + Integer.parseInt((String)Pregunta5.getSelectedItem())
            + Integer.parseInt((String)Pregunta6.getSelectedItem()));    
            PuntosAcumulados = PuntosAcumulados + (PuntosAcumuladosParciales*3);            
                                            
            tituloencuesta.setText("Habilidades del Postulante");
            p1.setText("<html><center>1. ¿Qué tanto aporte siente usted que realiza <br> en un equipo de trabajo?</center></html>");
            p2.setText("<html><center>2. ¿Qué tan hábil se siente para ser un líder <br> de trabajo?</center></html>");
            p3.setText("<html><center>3. ¿Qué tanto respeta las opiniones de los otros?</center></html>");
            p4.setText("<html><center>4. ¿Qué tan hábil es usted para no depender <br> de nadie en su trabajo?</center></html>");
            p5.setText("<html><center>5. ¿Qué tan efectivo se considera para convencer <br> a sus superiores?</center></html>");
            p6.setText("<html><center>6. ¿Qué tan autosuficiente se considera?</center></html>");
            Pregunta1.setSelectedIndex(0);
            Pregunta2.setSelectedIndex(0);
            Pregunta3.setSelectedIndex(0);
            Pregunta4.setSelectedIndex(0);
            Pregunta5.setSelectedIndex(0);
            Pregunta6.setSelectedIndex(0);
        }
        
        /*Habilidades*/        
        if (Referencia == 3){                   
            PuntosAcumuladosParciales = 0;
            PuntosAcumuladosParciales = PuntosAcumuladosParciales 
            + (Integer.parseInt((String)Pregunta1.getSelectedItem())
            + Integer.parseInt((String)Pregunta2.getSelectedItem())
            + Integer.parseInt((String)Pregunta3.getSelectedItem())
            + Integer.parseInt((String)Pregunta4.getSelectedItem())
            + Integer.parseInt((String)Pregunta5.getSelectedItem())
            + Integer.parseInt((String)Pregunta6.getSelectedItem()));
            
            tituloencuesta.setText("Habilidades del Postulante");
            p1.setText("<html><center>7. ¿Qué tan hábil se considera para lograr escalar <br> en la empresa?</center></html>");
            p2.setText("<html><center>8. ¿Qué nivel de autocontrol tiene?</center></html>");
            p3.setText("<html><center>9. ¿Qué tan persuasivo se considera?</center></html>");
            p4.setText("<html><center>10. ¿Qué tan creativo se considera?</center></html>");
            p5.setText("<html><center>11. ¿Qué nivel de manejo tiene con la tecnología <br> (software, hardware, etc.)?</center></html>");
            p6.setText("<html><center>12. ¿Considera que tiene habilidades para resolver <br> problemas?</center></html>");
            Pregunta1.setSelectedIndex(0);
            Pregunta2.setSelectedIndex(0);
            Pregunta3.setSelectedIndex(0);
            Pregunta4.setSelectedIndex(0);
            Pregunta5.setSelectedIndex(0);
            Pregunta6.setSelectedIndex(0);
            
        }
        
        /*Necesidades*/        
        if (Referencia == 4){            
            
            PuntosAcumuladosParciales = PuntosAcumuladosParciales 
            + (Integer.parseInt((String)Pregunta1.getSelectedItem())
            + Integer.parseInt((String)Pregunta2.getSelectedItem())
            + Integer.parseInt((String)Pregunta3.getSelectedItem())
            + Integer.parseInt((String)Pregunta4.getSelectedItem())
            + Integer.parseInt((String)Pregunta5.getSelectedItem())
            + Integer.parseInt((String)Pregunta6.getSelectedItem()));
            PuntosAcumulados = PuntosAcumulados + (PuntosAcumuladosParciales*2);
            
            PuntosAcumuladosParciales = 0;
                        
            tituloencuesta.setText("Necesidades del Postulante");
            p1.setText("<html><center>1. ¿Qué tan deseoso esta por trabajar acá?</center></html>");
            p2.setText("<html><center>2. ¿Qué tan motivado se siente?</center></html>");
            p3.setText("<html><center>3. ¿Qué tan importante es para usted este empleo?</center></html>");
            p4.setText("<html><center>4. ¿Cree que es bien considerado en la actualidad <br> por la empresa, tanto que consideren siempre sus proposiciones?</center></html>");
            p5.setText("<html><center>5. ¿Espera siempre recompensas al aportar con ideas <br> a la empresa?</center></html>");
            p6.setText("<html><center>6. ¿Qué tan deseoso esta por escalar en la empresa?</center></html>");
            Pregunta1.setSelectedIndex(0);
            Pregunta2.setSelectedIndex(0);
            Pregunta3.setSelectedIndex(0);
            Pregunta4.setSelectedIndex(0);
            Pregunta5.setSelectedIndex(0);
            Pregunta6.setSelectedIndex(0);
        }
        
        /*Necesidades*/        
        if (Referencia == 5){           
            
            PuntosAcumuladosParciales = 0;
            PuntosAcumuladosParciales = PuntosAcumuladosParciales 
            + (Integer.parseInt((String)Pregunta1.getSelectedItem())
            + Integer.parseInt((String)Pregunta2.getSelectedItem())
            + Integer.parseInt((String)Pregunta3.getSelectedItem())
            + Integer.parseInt((String)Pregunta4.getSelectedItem())
            + Integer.parseInt((String)Pregunta5.getSelectedItem())
            + Integer.parseInt((String)Pregunta6.getSelectedItem()));
            
            tituloencuesta.setText("Necesidades del Postulante");
            p1.setText("<html><center>7. ¿Qué nivel de importancia tiene para usted el dinero?</center></html>");
            p2.setText("<html><center>8. ¿Qué nivel de serenidad necesita para lograr <br> su 100% de rendimiento?</center></html>");
            p3.setText("<html><center>9. ¿Qué tan importante es para usted el <br> reconocimiento en la empresa?</center></html>");
            p4.setText("<html><center>10. ¿Cuánta confianza necesita para considerarse <br> seguro en su trabajo?</center></html>");
            p5.setText("<html><center>11. ¿Qué tan sociable se considera en la empresa?</center></html>");
            p6.setText("<html><center>12. ¿Que tanto busca el constante mejoraramiento?</center></html>");
            Pregunta1.setSelectedIndex(0);
            Pregunta2.setSelectedIndex(0);
            Pregunta3.setSelectedIndex(0);
            Pregunta4.setSelectedIndex(0);
            Pregunta5.setSelectedIndex(0);
            Pregunta6.setSelectedIndex(0);
            
        }
        
         /*Bibliograficas, Ambientales y Perfil*/        
        if (Referencia == 6){
            
            PuntosAcumuladosParciales = PuntosAcumuladosParciales 
            + (Integer.parseInt((String)Pregunta1.getSelectedItem())
            + Integer.parseInt((String)Pregunta2.getSelectedItem())
            + Integer.parseInt((String)Pregunta3.getSelectedItem())
            + Integer.parseInt((String)Pregunta4.getSelectedItem())
            + Integer.parseInt((String)Pregunta5.getSelectedItem())
            + Integer.parseInt((String)Pregunta6.getSelectedItem()));           
            PuntosAcumulados = PuntosAcumulados + (PuntosAcumuladosParciales*3);
            
            tituloencuesta.setText("Bibliograficas, Ambientales y Perfil del Postulante");
            p1.setText("<html><center>1. ¿Qué importancia le da usted a la vida en pareja?</center></html>");
            p2.setText("<html><center>2. ¿Le gusta como ha vivido su vida?</center></html>");
            p3.setText("<html><center>1. ¿Cuán consciente está usted de las leyes <br> ambientales del país que aplican a la empresa?</center></html>");
            p4.setText("<html><center>2. ¿Qué nivel de participación tiene usted <br> en el cuidado ambiental de la empresa?</center></html>");
            p5.setText("<html><center>1. ¿Necesita que le digan que hacer muy a <br> menudo?</center></html>");
            p6.setText("<html><center>2. ¿Qué nivel de importancia tiene el logro <br> de objetivos para usted?</center></html>");
            Pregunta1.setSelectedIndex(0);
            Pregunta2.setSelectedIndex(0);
            Pregunta3.setSelectedIndex(0);
            Pregunta4.setSelectedIndex(0);
            Pregunta5.setSelectedIndex(0);
            Pregunta6.setSelectedIndex(0);
            ImageIcon icono = new ImageIcon("src/Imagenes/resultado.png");
            next.setIcon(icono);            
            next.setText("Ver Resultados"); 
        }
        /*Condicion de Resultado*/
        if (Referencia == 7){             
            
            parar.setVisible(false);
            cancelar.setVisible(false);
            jLabel8.setVisible(false);
            
            PuntosAcumuladosParciales = 0;
            PuntosAcumuladosParciales = PuntosAcumuladosParciales 
            + ((Integer.parseInt((String)Pregunta1.getSelectedItem()) + Integer.parseInt((String)Pregunta2.getSelectedItem())) * 1)
            + ((Integer.parseInt((String)Pregunta3.getSelectedItem()) + Integer.parseInt((String)Pregunta4.getSelectedItem())) * 2)
            + ((Integer.parseInt((String)Pregunta5.getSelectedItem()) + Integer.parseInt((String)Pregunta6.getSelectedItem())) * 3);           
                        
            PuntosAcumulados = PuntosAcumulados + PuntosAcumuladosParciales;            
            
            /*Seccion de Seleccion de Rol*/
            tituloencuesta.setText("!!Resultados de la Encuesta!!");
            Pregunta1.setVisible(false);
            Pregunta2.setVisible(false);
            Pregunta3.setVisible(false);
            Pregunta4.setVisible(false);
            Pregunta5.setVisible(false);
            Pregunta6.setVisible(false);
            p3.setVisible(false);           
            jSeparator3.setVisible(false);
            jSeparator4.setVisible(false);
            jSeparator5.setVisible(false);
            next.setText("Volver al Menú");       
            
            ImageIcon icono = new ImageIcon("src/Imagenes/menu.png");
            next.setIcon(icono);
            p1.setFont( new Font( "Verdana",Font.BOLD,14 ) );
            p2.setFont( new Font( "Trebuchet",Font.PLAIN,16 ) );
            String numCadena= String.valueOf(PuntosAcumulados);
            String Cadena = "<html><center>¡¡Felicitaciones!! <br> El puntaje obtenido fue: " + numCadena + "</center></html>" ;
            p1.setText(Cadena);
 
            if(PuntosAcumulados >= 108 && PuntosAcumulados <= 215){               
                p2.setText("<html><center>El cargo o Rol óptimo que puede el postulante <br> desarrollar en la empresa, basado en sus Competencias, <br> Necesidades Habilidades y otros críterios es <b>Auxiliar de Aseo </b></center></html>");
            }
            
            else if(PuntosAcumulados >= 216 && PuntosAcumulados <= 323){
                p2.setText("<html><center>El cargo o Rol óptimo que puede el postulante <br> desarrollar en la empresa, basado en sus Competencias, <br> Necesidades Habilidades y otros críterios es <b>Reponedor </b></center></html>");
            }
            
            else if(PuntosAcumulados >= 324 && PuntosAcumulados <= 431){
                p2.setText("<html><center>El cargo o Rol óptimo que puede el postulante <br> desarrollar en la empresa, basado en sus Competencias, <br> Necesidades Habilidades y otros críterios es <b>Guardia </b></center></html>");
            }
            
            else if(PuntosAcumulados >= 432 && PuntosAcumulados <= 539){
                p2.setText("<html><center>El cargo o Rol óptimo que puede el postulante <br> desarrollar en la empresa, basado en sus Competencias, <br> Necesidades Habilidades y otros críterios es <b>Operador de Maquinas </b></center></html>");
            }
            
            else if(PuntosAcumulados >= 540 && PuntosAcumulados <= 647){
                p2.setText("<html><center>El cargo o Rol óptimo que puede el postulante <br> desarrollar en la empresa, basado en sus Competencias, <br> Necesidades Habilidades y otros críterios es <b>Secretaria </b></center></html>");
            }
            
            else if(PuntosAcumulados >= 648 && PuntosAcumulados <= 755){
                p2.setText("<html><center>El cargo o Rol óptimo que puede el postulante <br> desarrollar en la empresa, basado en sus Competencias, <br> Necesidades Habilidades y otros críterios es <b>Vendedor </b></center></html>");
            }
            
            else if(PuntosAcumulados >= 756 && PuntosAcumulados <= 791){
                p2.setText("<html><center>El cargo o Rol óptimo que puede el postulante <br> desarrollar en la empresa, basado en sus Competencias, <br> Necesidades Habilidades y otros críterios es <b>Encargado de Seguridad </b></center></html>");
            }
            
            else if(PuntosAcumulados >= 792 && PuntosAcumulados <= 827){
                p2.setText("<html><center>El cargo o Rol óptimo que puede el postulante <br> desarrollar en la empresa, basado en sus Competencias, <br> Necesidades Habilidades y otros críterios es <b>Encargado de Maquinas </b></center></html>");
            }
            
            else if(PuntosAcumulados >= 828 && PuntosAcumulados <= 863){
                p2.setText("<html><center>El cargo o Rol óptimo que puede el postulante <br> desarrollar en la empresa, basado en sus Competencias, <br> Necesidades Habilidades y otros críterios es <b>Encargado de Personal </b></center></html>"); 
            }
            
            else if(PuntosAcumulados >= 864 && PuntosAcumulados <= 899){
                p2.setText("<html><center>El cargo o Rol óptimo que puede el postulante <br> desarrollar en la empresa, basado en sus Competencias, <br> Necesidades Habilidades y otros críterios es <b>Coordinador </b></center></html>");
            }
            
            else if(PuntosAcumulados >= 900 && PuntosAcumulados <= 935){
                p2.setText("<html><center>El cargo o Rol óptimo que puede el postulante <br> desarrollar en la empresa, basado en sus Competencias, <br> Necesidades Habilidades y otros críterios es <b>Encargado de Local </b></center></html>");
            }
            
            else if(PuntosAcumulados >= 936 && PuntosAcumulados <= 971){
                p2.setText("<html><center>El cargo o Rol óptimo que puede el postulante <br> desarrollar en la empresa, basado en sus Competencias, <br> Necesidades Habilidades y otros críterios es <b>Auditoria </b></center></html>"); 
            }
            
            else if(PuntosAcumulados >= 972 && PuntosAcumulados <= 989){
                p2.setText("<html><center>El cargo o Rol óptimo que puede el postulante <br> desarrollar en la empresa, basado en sus Competencias, <br> Necesidades Habilidades y otros críterios es <b>Gerente de Fiscalia </b></center></html>");
            }
            
            else if(PuntosAcumulados >= 990 && PuntosAcumulados <= 1007){
                p2.setText("<html><center>El cargo o Rol óptimo que puede el postulante <br> desarrollar en la empresa, basado en sus Competencias, <br> Necesidades Habilidades y otros críterios es <b>Gerente de Marketing </b></center></html>");
            }
            
            else if(PuntosAcumulados >= 1008 && PuntosAcumulados <= 1025){
                p2.setText("<html><center>El cargo o Rol óptimo que puede el postulante <br> desarrollar en la empresa, basado en sus Competencias, <br> Necesidades Habilidades y otros críterios es <b>Gerente de RRHH </b></center></html>");
            }
            
            else if(PuntosAcumulados >= 1026 && PuntosAcumulados <= 1043){
                p2.setText("<html><center>El cargo o Rol óptimo que puede el postulante <br> desarrollar en la empresa, basado en sus Competencias, <br> Necesidades Habilidades y otros críterios es <b>Gerente de Operaciones </b></center></html>");
            }
            
            else if(PuntosAcumulados >= 1044 && PuntosAcumulados <= 1061){
                p2.setText("<html><center>El cargo o Rol óptimo que puede el postulante <br> desarrollar en la empresa, basado en sus Competencias, <br> Necesidades Habilidades y otros críterios es <b>Gerente de Finanzas </b></center></html>"); 
            }
            
             else if(PuntosAcumulados >= 1062 && PuntosAcumulados <= 1080){
                p2.setText("<html><center>El cargo o Rol óptimo que puede el postulante <br> desarrollar en la empresa, basado en sus Competencias, <br> Necesidades Habilidades y otros críterios es <b>Gerente General </b></center></html>");
            }
            
            /*FIN Seccion de Seleccion de Rol*/ 
            
            
            p3.setText("<html><center></center></html>");
            p4.setText("<html><center></center></html>");
            p5.setText("<html><center></center></html>");
            p6.setText("<html><center></center></html>");
            PuntosAcumuladosParciales = 0;
            PuntosAcumulados= 0;
        }
        
        /*Condicion de Salida*/
        if (Referencia == 8){        
            
            Referencia = 0; 
            Inicio ventana = new Inicio();
            this.dispose();
            Encuesta.setDefaultLookAndFeelDecorated(true);
            ventana.setVisible(true);
            ventana.setResizable(false);
            ventana.setLocationRelativeTo(null);
            ventana.setDefaultCloseOperation(Encuesta.DO_NOTHING_ON_CLOSE);
            ventana.setTitle("Encuesta | Postulante");
            Image icono;
            icono = Toolkit.getDefaultToolkit().getImage("src/Imagenes/rol.png");
            ventana.setIconImage(icono);
            ventana.getRootPane().setFont(UIManager.getFont("SystemFont"));        
        }     
    }//GEN-LAST:event_nextActionPerformed

    private void pararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pararActionPerformed
        // TODO add your handling code here:
        Inicio ventana = new Inicio();
        this.dispose();
        Encuesta.setDefaultLookAndFeelDecorated(true);
        ventana.setVisible(true);
        ventana.setResizable(false);
        ventana.setLocationRelativeTo(null);
        ventana.setDefaultCloseOperation(Encuesta.DO_NOTHING_ON_CLOSE);
        ventana.setTitle("Encuesta | Postulante");
        Image icono;
        icono = Toolkit.getDefaultToolkit().getImage("src/Imagenes/rol.png");
        ventana.setIconImage(icono);
        ventana.getRootPane().setFont(UIManager.getFont("SystemFont"));
        PuntosAcumuladosParciales = 0;
        PuntosAcumulados = 0;
        Referencia = 0;
    }//GEN-LAST:event_pararActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Encuesta().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Pregunta1;
    private javax.swing.JComboBox Pregunta2;
    private javax.swing.JComboBox Pregunta3;
    private javax.swing.JComboBox Pregunta4;
    private javax.swing.JComboBox Pregunta5;
    private javax.swing.JComboBox Pregunta6;
    private javax.swing.JLabel cancelar;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JButton next;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p2;
    private javax.swing.JLabel p3;
    private javax.swing.JLabel p4;
    private javax.swing.JLabel p5;
    private javax.swing.JLabel p6;
    private javax.swing.JButton parar;
    private javax.swing.JLabel tituloencuesta;
    // End of variables declaration//GEN-END:variables
}
