/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.UIManager;

/**
 *
 * @author John
 */
public class Encuesta extends javax.swing.JFrame {
public static int Referencia = 0;
public static int PuntosAcumulados = 0;
    /**
     * Creates new form Encuesta01
     */
    public Encuesta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloencuesta = new javax.swing.JLabel();
        p1 = new javax.swing.JLabel();
        p6 = new javax.swing.JLabel();
        p2 = new javax.swing.JLabel();
        p3 = new javax.swing.JLabel();
        p4 = new javax.swing.JLabel();
        p5 = new javax.swing.JLabel();
        Pregunta1 = new javax.swing.JComboBox();
        Pregunta2 = new javax.swing.JComboBox();
        Pregunta3 = new javax.swing.JComboBox();
        Pregunta5 = new javax.swing.JComboBox();
        Pregunta6 = new javax.swing.JComboBox();
        Pregunta4 = new javax.swing.JComboBox();
        next = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        parar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(358, 18));
        setName("[358, 18]"); // NOI18N

        tituloencuesta.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        tituloencuesta.setText("Competencias del Postulante");

        p1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        p1.setText("1. ¿Cuánta experiencia cree tener en su área de trabajo?");
        p1.setMaximumSize(new java.awt.Dimension(433, 64));
        p1.setMinimumSize(new java.awt.Dimension(358, 18));
        p1.setName("[358, 18]"); // NOI18N

        p6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        p6.setText("6. ¿Qué nivel de aprendizaje cree que usted tiene?");
        p6.setMaximumSize(new java.awt.Dimension(358, 18));
        p6.setMinimumSize(new java.awt.Dimension(358, 18));
        p6.setName("[358, 18]"); // NOI18N

        p2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        p2.setText("2. ¿Cuanto ha tratado de mejorar en su área de trabajo?");
        p2.setMaximumSize(new java.awt.Dimension(358, 18));
        p2.setMinimumSize(new java.awt.Dimension(358, 18));
        p2.setName("[358, 18]"); // NOI18N

        p3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        p3.setText("3. ¿Tiene grandes ganas de trabajar, le entusiasma lo que hace?");
        p3.setMaximumSize(new java.awt.Dimension(358, 18));
        p3.setMinimumSize(new java.awt.Dimension(358, 18));
        p3.setName("[358, 18]"); // NOI18N

        p4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        p4.setText("4. ¿Que tanto se adapta al ritmo de la empresa?");
        p4.setMaximumSize(new java.awt.Dimension(358, 18));
        p4.setMinimumSize(new java.awt.Dimension(358, 18));
        p4.setName("[358, 18]"); // NOI18N

        p5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        p5.setText("5. ¿Qué tan empático se considera?");
        p5.setMaximumSize(new java.awt.Dimension(358, 18));
        p5.setMinimumSize(new java.awt.Dimension(358, 18));
        p5.setName("[358, 18]"); // NOI18N

        Pregunta1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10" }));
        Pregunta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pregunta1ActionPerformed(evt);
            }
        });

        Pregunta2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10" }));
        Pregunta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pregunta2ActionPerformed(evt);
            }
        });

        Pregunta3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10" }));
        Pregunta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pregunta3ActionPerformed(evt);
            }
        });

        Pregunta5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10" }));
        Pregunta5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pregunta5ActionPerformed(evt);
            }
        });

        Pregunta6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10" }));
        Pregunta6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pregunta6ActionPerformed(evt);
            }
        });

        Pregunta4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10" }));
        Pregunta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pregunta4ActionPerformed(evt);
            }
        });

        next.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/siguiente.png"))); // NOI18N
        next.setText("Siguiente");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/competencias.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");

        parar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/parar.png"))); // NOI18N
        parar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pararActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel1.setText("Cancelar Encuesta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tituloencuesta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(parar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(p3, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                            .addComponent(p4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(p2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(p6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(p5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(p1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pregunta1, 0, 83, Short.MAX_VALUE)
                            .addComponent(Pregunta2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pregunta3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pregunta5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pregunta6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pregunta4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(next, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(tituloencuesta)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pregunta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pregunta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pregunta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pregunta4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pregunta5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pregunta6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(next)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Pregunta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pregunta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pregunta1ActionPerformed

    private void Pregunta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pregunta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pregunta2ActionPerformed

    private void Pregunta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pregunta3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pregunta3ActionPerformed

    private void Pregunta5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pregunta5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pregunta5ActionPerformed

    private void Pregunta6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pregunta6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pregunta6ActionPerformed

    private void Pregunta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pregunta4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pregunta4ActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        Referencia++;
        PuntosAcumulados = PuntosAcumulados 
        + (Integer.parseInt((String)Pregunta1.getSelectedItem())
        + Integer.parseInt((String)Pregunta2.getSelectedItem())
        + Integer.parseInt((String)Pregunta3.getSelectedItem())
        + Integer.parseInt((String)Pregunta4.getSelectedItem())
        + Integer.parseInt((String)Pregunta5.getSelectedItem())
        + Integer.parseInt((String)Pregunta6.getSelectedItem()));
        System.out.println("Hola "+ PuntosAcumulados);
        /*Competencias*/        
        if (Referencia == 1){
            tituloencuesta.setText("Competencias del Postulante");
            p1.setText("<html><center>7. ¿Qué nivel de adaptación al ambiente laboral posee?</center></html>");
            p2.setText("<html><center>8. ¿Qué tan líder usted podría ser?</center></html>");
            p3.setText("<html><center>9. ¿Qué tan a menudo prevé cambios a futuro?</center></html>");
            p4.setText("<html><center>10. ¿Posee capacidades para la negociación?</center></html>");
            p5.setText("<html><center>11. ¿Cree ser capaz de dominar la materia que <br>le competerá, para poder lidiar con una orientación <br> o guía al cliente de manera exitosa?</center></html>");
            p6.setText("<html><center>12. ¿Qué tan bien puede usted manejar la presión en<br> el ambiente laboral?</center></html>");
            Pregunta1.setSelectedIndex(0);
            Pregunta2.setSelectedIndex(0);
            Pregunta3.setSelectedIndex(0);
            Pregunta4.setSelectedIndex(0);
            Pregunta5.setSelectedIndex(0);
            Pregunta6.setSelectedIndex(0);
        }
        
    }//GEN-LAST:event_nextActionPerformed

    private void pararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pararActionPerformed
        // TODO add your handling code here:
       Inicio ventana = new Inicio();
        //setVisible(false);
        this.dispose();
        Encuesta.setDefaultLookAndFeelDecorated(true);
        ventana.setVisible(true);
        ventana.setResizable(false);
        ventana.setLocationRelativeTo(null);
        ventana.setDefaultCloseOperation(Encuesta.DO_NOTHING_ON_CLOSE);
        ventana.setTitle("Encuesta | Postulante");
        Image icono;
        icono = Toolkit.getDefaultToolkit().getImage("src/Imagenes/rol.png");
        ventana.setIconImage(icono);
        ventana.getRootPane().setFont(UIManager.getFont("SystemFont")); 
    }//GEN-LAST:event_pararActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Encuesta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Pregunta1;
    private javax.swing.JComboBox Pregunta2;
    private javax.swing.JComboBox Pregunta3;
    private javax.swing.JComboBox Pregunta4;
    private javax.swing.JComboBox Pregunta5;
    private javax.swing.JComboBox Pregunta6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton next;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p2;
    private javax.swing.JLabel p3;
    private javax.swing.JLabel p4;
    private javax.swing.JLabel p5;
    private javax.swing.JLabel p6;
    private javax.swing.JButton parar;
    private javax.swing.JLabel tituloencuesta;
    // End of variables declaration//GEN-END:variables
}
